### ISSUE TITLE
Offizielle Treffen anpassen

### ISSUE THREAD

**Issue by Tarnatos** [rubo77/freifunk-faltblatt-6-seiten#11]
Moin Ruben,

das offizielle Treffen ist doch noch jeden 1. Do im Monat. Das imho sollte angepasst werden.

**Comment by rubo77** [comment]
nee es ist ja so, dass ich eigentlich immer montags und donnerstags dort bin, insofern ist dann auch Treffen :)

Oder wie könnte man das auf dem Flyer komprieren?

**Comment by Tarnatos** [comment]
Ah ok.

Sowas wie:

Freifunk Treffen: Jeden ersten Donnerstag im Monat 20:00 Uhr Top....
Starthilfe: Jeden Mo. und Do. ab 20:00 ....

**Comment by Tarnatos** [comment]
@rubo77 

Kannst du das bitte noch anpassen?

Freifunk Treffen: Jeden ersten Donnerstag im Monat 20:00 Uhr Top....
Twitter entfernen
Email auf  kontakt@freifunknord.de ändern
Chat auf chat.freifunknord.de ändern (hab ich angelegt)

Danke.

**Comment by rubo77** [comment]
done
